### ISSUE TITLE
Filename of main .ino file doesn't match directory name

### ISSUE THREAD

**Issue by omgitsraven** [TinyCircuits/TinyCircuits-TinyTVs-Firmware#4]
When I check out the project and try to open it in Arduino IDE, it complains that it needs to be in a directory that matches its name;  currently, the .ino file is named
`TinyCircuits-TinyTVs-Firmware-merge`
and the directory (when named after the repo, as git typically does) is named
`TinyCircuits-TinyTVs-Firmware`
Should I put in a pull request that would remove the `-merge` suffix from the .ino file?

**Comment by broseTC** [comment]
Thanks!
